<?php
$posts = Mage::getModel('blog/blog')
            ->getCollection()
            ->addPresentFilter()
            ->addStoreFilter(Mage::app()->getStore()->getId())
            ->addFieldToFilter('status', 1)
            ->setOrder('created_time ', 'desc')
            ->setPageSize(3);
if(count($posts)):                   
?>
    
    <?php foreach ($posts as $post): ?>
    
    <div class="item">
                                            <div class="item-inner">
                                                <div class="blog-image">
                                                    <a href="<?php echo $this->getBaseUrl().'blog/'.$post->getIdentifier(); ?>">
                                                        <?php echo $this->helper('cms')->getBlockTemplateProcessor()->filter($post->getShortContent()); ?>
                                                    </a>
                                                    
                                                </div>
                                                <div class="blog-content">
                                                    <div class="time-conment">
														<?php echo $this->formatDate($post->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), true); ?>
<!--
                                                       <span class="date-time"><span class="date">08</span><span class="separator">/</span><span class="month">September</span>/</span><span class="year">2016</span>
-->
                                                    </div>	
                                                    <div class="blog-content-inner">
                                                         <h3 class="blog-title"><a href="#"><?php echo $post->getTitle(); ?></a></h3> 
                                                                                             
                                                        <p class="short-des"><?php echo $this->helper('cms')->getBlockTemplateProcessor()->filter($post->getPostContent()); ?></p>
                                                        <a class="readmore" href="<?php echo $this->getBaseUrl().'blog/'.$post->getIdentifier(); ?>">
                                                            Read more<i class="fa fa-long-arrow-right"></i>
                                                        </a>
                                                    </div>
                                                    
                                                </div>
                                            </div>
                                        </div>
    
    
    
<!--
        <li>
            <div class="postContent std"><?php echo $this->helper('cms')->getBlockTemplateProcessor()->filter($post->getShortContent()); ?></div>
            <a href="<?php echo $this->getBaseUrl().'blog/'.$post->getIdentifier(); ?>"><?php echo $post->getTitle(); ?></a>
            (<?php echo $this->formatDate($post->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), true); ?>)
        </li>
-->
    <?php endforeach; ?>
    
<?php endif;?>
